In [1]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

In [2]:
result = pd.read_csv('result.csv',index_col=0)
result = result.T
result.columns = "AR WR PtoA PHtP AHTAL".split()
result.head()

AR        WR      PtoA      PHtP     AHTAL
0  1.144022  0.718679  0.011543  0.935736  0.993181
1  1.355263  0.670869  0.013844  0.935623  0.985451
2  1.178470  0.720905  0.011862  0.942243  0.993329
3  1.123596  0.692026  0.012333  0.939155  0.989775
4  1.151596  0.684229  0.011723  0.934796  0.990750

In [3]:
hist = pd.read_csv('histo.csv',index_col=0)

In [4]:
column = []
for i in range(0,768):
    column.append('c'+str(i))
    
hist.columns=column

In [5]:
hist.head()

c0   c1   c2   c3   c4   c5   c6   c7   c8   c9  ...     c758    c759  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   1743.0  2096.0   
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    614.0   223.0   
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   5537.0  6390.0   
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   2498.0  2918.0   
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   1017.0  1528.0   

     c760    c761    c762    c763    c764    c765     c766  c767  
0  2583.0  3515.0  4226.0  5155.0  6253.0  6900.0   7479.0   0.0  
0    36.0     7.0     1.0     1.0     0.0     0.0      0.0   0.0  
0  6495.0  6225.0  4841.0  3542.0  2546.0  1769.0   1148.0   0.0  
0  4145.0  6749.0  9237.0  9989.0  6961.0  3295.0   1409.0   0.0  
0  2046.0  2377.0  2267.0  2440.0  3219.0  5682.0  11743.0   0.0  

[5 rows x 768 columns]

In [6]:
hog = pd.read_csv('hog_gray.csv',index_col=0)
cols = []
for i in range(len(hog.columns)):
    cols.append('hog'+str(i))
hog.columns=cols

In [7]:
hist['AR']=np.array(result['AR'])
hist['WR']=np.array(result['WR'])
hist['PtoA']=np.array(result['PtoA'])
hist['PHtP']=np.array(result['PHtP'])
hist['AHTAL']=np.array(result['AHTAL'])
for i in hog.columns:
    hist[i] = hog[i]

In [8]:
hist

c0   c1   c2   c3   c4   c5   c6   c7    c8    c9   ...       hog27  \
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      971946   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      682451   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      712911   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      876228   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      758758   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      529140   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      943263   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      674619   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      807023   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      655015   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      565085   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      588243   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      662494   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      877604   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      505217   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      732172   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...     1059760   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      619574   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      819016   
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      794941   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...     1334573   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...     1028084   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      842659   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      922742   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      711400   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...     1182801   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...     1289999   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      816100   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      972502   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      978762   
..  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...         ...   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      896930   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   2.0  11.0   ...      418320   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      815790   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      650482   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      810901   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   3.0  22.0   ...      475786   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      681361   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   4.0  36.0   ...      607279   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      419843   
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0   4.0   ...      552999   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      644763   
31  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  12.0   9.0   ...      766752   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      409790   
31  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   0.0   2.0   ...      452157   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      716368   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      916857   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      689297   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      951146   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      802113   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0   ...      953164   
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.

In [9]:
index=hist.index

In [10]:
df=hist

In [11]:
hist.to_csv('final_result.csv')

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df,index,
                                                    test_size=0.25,random_state=401)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
error_rate = []

# Will take some time
for i in range(1,20):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

In [19]:
plt.figure(figsize=(10,6))
plt.plot(range(1,20),error_rate,color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')
plt.savefig('error_vs_k.png')

In [20]:
knn = KNeighborsClassifier(n_neighbors=3)

In [21]:
knn.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [22]:
pred = knn.predict(X_test)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix


In [24]:
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

[[5 0 0 ..., 0 0 1]
 [1 3 0 ..., 0 0 0]
 [0 0 6 ..., 0 0 0]
 ..., 
 [0 1 0 ..., 2 0 0]
 [0 0 0 ..., 0 4 0]
 [1 0 0 ..., 0 0 5]]
             precision    recall  f1-score   support

          0       0.50      0.83      0.62         6
          1       0.60      0.60      0.60         5
          2       0.75      0.86      0.80         7
          3       0.71      1.00      0.83         5
          4       1.00      1.00      1.00         2
          5       0.29      1.00      0.44         4
          6       1.00      0.60      0.75         5
          7       1.00      1.00      1.00         5
          8       0.50      0.80      0.62         5
          9       1.00      1.00      1.00         3
         10       0.50      1.00      0.67         3
         11       1.00      1.00      1.00         4
         12       0.71      1.00      0.83         5
         13       0.75      0.50      0.60         6
         14       1.00      1.00      1.00         5
         15       0.67 

0.71875

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(hist,index,
                                                    test_size=0.25,random_state=301)
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
pred = clf.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[7 0 0 ..., 0 0 0]
 [0 4 0 ..., 0 0 0]
 [0 0 1 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 6 0 0]
 [0 0 0 ..., 0 7 0]
 [0 0 0 ..., 0 0 4]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       0.67      1.00      0.80         4
          2       0.33      0.33      0.33         3
          3       0.25      0.17      0.20         6
          4       1.00      0.50      0.67         8
          5       0.40      1.00      0.57         2
          6       1.00      1.00      1.00         2
          7       0.75      0.75      0.75         8
          8       1.00      1.00      1.00         4
          9       1.00      0.67      0.80         3
         10       0.75      0.67      0.71         9
         11       0.83      0.83      0.83         6
         12       0.50      0.25      0.33         4
         13       0.67      0.67      0.67         3
         14       0.67      0.50      0.57         4
         15       0.38 

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.67500000000000004

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rfc = RandomForestClassifier(n_estimators=400)

In [29]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=400, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [30]:
pred = rfc.predict(X_test)

In [31]:
species = pd.read_csv('species.csv',index_col=0)
species.columns = ['spec']
l = species['spec']

In [32]:
print(X_test)

     c0    c1    c2    c3     c4     c5     c6     c7     c8     c9   ...     \
13  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
26  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
10  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
11  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
15  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
22  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
16  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
17  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
3   0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
19  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
22  0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   ...      
3   0.0   0.0   0.0   0.0    0.0    0.0 

In [33]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

for i in range(len(y_test)):
    print("y_test = "+l[y_test[i]]+"    pred = "+l[pred[i]])

[[6 0 0 ..., 0 0 0]
 [0 2 0 ..., 0 0 0]
 [0 0 3 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 6 0 1]
 [0 0 0 ..., 0 7 0]
 [0 0 0 ..., 0 0 4]]
             precision    recall  f1-score   support

          0       0.86      0.86      0.86         7
          1       1.00      0.50      0.67         4
          2       0.60      1.00      0.75         3
          3       1.00      0.83      0.91         6
          4       0.62      0.62      0.62         8
          5       1.00      1.00      1.00         2
          6       1.00      1.00      1.00         2
          7       1.00      1.00      1.00         8
          8       1.00      1.00      1.00         4
          9       0.75      1.00      0.86         3
         10       1.00      0.67      0.80         9
         11       1.00      1.00      1.00         6
         12       0.80      1.00      0.89         4
         13       1.00      0.33      0.50         3
         14       1.00      1.00      1.00         4
         15       1.00 

In [34]:
from sklearn.metrics import classification_report,confusion_matrix

In [35]:
randFor = rfc = RandomForestClassifier(n_estimators=400)
randFor.fit(df,index)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=400, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [36]:
import pickle

In [37]:
pickle.dump(randFor, open('Forest_Regression_Classifier.sav', 'wb'))

In [38]:
loaded_model = pickle.load(open('Forest_Regression_Classifier.sav', 'rb'))
result = loaded_model.predict(X_test)
print(classification_report(y_test,result))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       1.00      1.00      1.00         4
          2       1.00      1.00      1.00         3
          3       1.00      1.00      1.00         6
          4       1.00      1.00      1.00         8
          5       1.00      1.00      1.00         2
          6       1.00      1.00      1.00         2
          7       1.00      1.00      1.00         8
          8       1.00      1.00      1.00         4
          9       1.00      1.00      1.00         3
         10       1.00      1.00      1.00         9
         11       1.00      1.00      1.00         6
         12       1.00      1.00      1.00         4
         13       1.00      1.00      1.00         3
         14       1.00      1.00      1.00         4
         15       1.00      1.00      1.00         6
         16       1.00      1.00      1.00         3
         17       1.00      1.00      1.00   

In [39]:
error = []
i = 25
while i<=500:
    rfc = RandomForestClassifier(n_estimators=i)
    rfc.fit(X_train,y_train)
    pred_i = rfc.predict(X_test)
    error.append(np.mean(pred_i != y_test))
    i+=25

In [40]:

plt.plot(range(1,500,25),error)
plt.title('Error vs. N estimators')
plt.xlabel('N estimator')
plt.ylabel('Error')
plt.savefig('error_vs_n_estimators.png')

In [58]:
import cv2
import math as m

name = '20150524_182648.jpg'
#reading the image
img1=cv2.imread(name)
        
        #RESIZING image to size (512,512) pi
img512= cv2.resize(img1,(512,512))

        
        #GRAYSCALING
imggray=cv2.cvtColor(img512,cv2.COLOR_BGR2GRAY)
        
        #THRESHOLDING
ret,imgthresh=cv2.threshold(imggray,125,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
        
        #OPENING Operation
kernel = np.ones((8,8),np.uint8)
opening = cv2.morphologyEx(imgthresh, cv2.MORPH_OPEN, kernel)       
        #INVERSE THRESHOLDING
ret2,threshInv = cv2.threshold(opening,0,255,cv2.THRESH_BINARY_INV)
        #EROSION, to remove some of the pre-processing noise
opening2 = cv2.erode(threshInv,kernel,iterations=1)        

        #NORMALIZE image to Dtype=8U
image = cv2.normalize(src=opening2, dst=None, alpha=0, beta=255,norm_type=cv2.NORM_MINMAX,dtype=cv2.CV_8UC1)
        
        #Finding CONTOURS
ret,contours,hierarchy = cv2.findContours(image, 1, 2)
     
        #Finding AREA using Moments(using Contours)
area=cv2.moments(contours[0])['m00']
        
        #Finding PERIMETER
perimeter=cv2.arcLength(contours[0],True)
        
        #Estimating CONVEX HULL

cnt = contours[0]
hull = cv2.convexHull(cnt)

        
        #Finding Hull_Area and Hull_Perimeter
hull_area = cv2.contourArea(hull)
hull_peri=cv2.arcLength(hull,True)
        
        #Making a bounding rectangle using contours and estimating width and height of the box
x,y,w,h = cv2.boundingRect(contours[0])
cv2.rectangle(img512,(x,y),(x+w,y+h),(0,255,0),2)


hist1 = cv2.calcHist([img512],[0],None,[256],[0,255])
hist2 = cv2.calcHist([img512],[1],None,[256],[0,255])
hist3 = cv2.calcHist([img512],[2],None,[256],[0,255])

feat = []
feat.extend(hist1)
feat.extend(hist2)
feat.extend(hist3)
feat.append((float(w)/h))
feat.append((float(area)/(w*h)))
feat.append(float(perimeter)/area)
feat.append(float(hull_peri)/perimeter)
feat.append(float(area)/hull_area)

img = cv2.GaussianBlur(img1,(5,5),0)
img = cv2.resize(img,(512,512))
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
        

mag, angle = cv2.cartToPolar(sobelx,sobely,angleInDegrees=True)
        
hog = []

for pop in range(0,361):
    hog.append(0)
    
hog = np.array(hog)

for k in range(0,64):
    for l in range(0,64):
        x = angle[k][l][0]
        y = int(m.floor(x))
        z = int(m.ceil(x))
        
        if x==y or x==z:
            hog[y] += mag[k][l][0]
        else:
            floor_a = x-y
            floor_b = z-x
            
            hog[y] += floor_b * mag[k][l][0]
            hog[z] += floor_a * mag[k][l][0]
feat.extend(hog)

species = pd.read_csv('species.csv',index_col=0)
species.columns=['name']
l = species['name']

rfc = RandomForestClassifier(n_estimators=175)
rfc.fit(X_train,y_train)
pred_i = rfc.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(l[pred[0]])

guava


HOG GRAy

In [19]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=400)
rfc.fit(X_train,y_train)
pred = rfc.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[7 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 2 ... 0 1 0]
 ...
 [0 0 0 ... 6 0 1]
 [0 0 0 ... 0 7 0]
 [0 0 0 ... 0 0 4]]
             precision    recall  f1-score   support

          0       0.88      1.00      0.93         7
          1       0.75      0.75      0.75         4
          2       1.00      0.67      0.80         3
          3       1.00      0.67      0.80         6
          4       0.75      0.43      0.55         7
          5       1.00      1.00      1.00         2
          6       0.50      1.00      0.67         2
          7       1.00      1.00      1.00         8
          8       1.00      1.00      1.00         4
          9       1.00      1.00      1.00         3
         10       1.00      0.78      0.88         9
         11       1.00      1.00      1.00         6
         12       1.00      1.00      1.00         4
         13       0.67      1.00      0.80         2
         14       1.00      1.00      1.00         5
         15       0.83      0.8

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred,normalize=True)

0.8616352201257862